### ISSUE TITLE
WIFI AP IP change and password

### ISSUE THREAD

**Issue by rodolfo61** [lucabarsanti/ESP32_YT_Button#2]
Where can I change the IP address that is assigned to the website in setup mode?
the password assigned by default (123456789) is not correct, is it possible to set a different one in the code?

**Comment by lucabarsanti** [comment]
I checked and the default password the same of SSID.
[    boolean result = WiFi.softAP("YoutubeButton", "YoutubeButton");](https://github.com/lucabarsanti/ESP32_YT_Button/blob/675f5a863e7e34640867406725d19ffc2b4d7725/FirmwareESP32/src/main.cpp#L169)
WiFi.softAP // the parameters within this function, identifies the WiFi SSID and Password.


I have not tested it but to change the ip address you have to:
```
IPAddress Ip(192, 168, 1, 1);
IPAddress NMask(255, 255, 255, 0);
WiFi.softAPConfig(Ip, Ip, NMask);
```

Before launching this command, you must activate the access point (softAP) and wait for the actual activation (I think it is enough to put a delay of about 150ms)

Let me know if it works!
